spring:
  datasource:
    url: jdbc:h2:mem:bozahouse
    driverClassName: org.h2.Driver
    username: user
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      open-in-view: false

  h2:
    console:
      enabled: true


  mail:
    host: smtp.bozahouse.com
    port: 587
    username: support@bozahouse.com
    password: Lwspanel@@2003
    protocol: smtp
  properties:
    mail:
      smtp:
        auth: true
        starttls:
        enable: true
      debug: true

server:
  port: 8085


  #swagger params
spring-doc:
  api-docs:
    path: /api-docs


url_backend: http://localhost:8085

  # App Properties
bozahouse:
  app:
    jwtSecret: bozahouseSecretKey
    jwtExpirationMs: 86400000


email_admin: support@bozahouse.com



