spring:
  datasource:
    url: jdbc:mysql://localhost:3306/host
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: pwd

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect



  mail:
    host: smtp.host.com
    port: 587
    username: name@host.com
    password: pwd
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
server:
  port: 8085
  
  
  #swagger params
spring-doc:
  api-docs:
    path: /api-docs
  
url_backend: https://api.host.com

  
  # App Properties
host:
  app:
    jwtSecret: hostSecretKey
    jwtExpirationMs: 86400000


email_admin: name@host.com



