spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bozahouse
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Bozahouse@@2003

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect



  mail:
    host: smtp.bozahouse.com
    port: 587
    username: support@bozahouse.com
    password: Lwspanel@@2003
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
server:
  port: 8085
  
  
  #swagger params
spring-doc:
  api-docs:
    path: /api-docs
  
url_backend: https://api.bozahouse.com

  
  # App Properties
bozahouse:
  app:
    jwtSecret: bozahouseSecretKey
    jwtExpirationMs: 86400000


email_admin: support@bozahouse.com



